import = [
  "~/.config/alacritty/themes/themes/rose-pine.toml"
  # "~/.config/alacritty/themes/themes/rose-pine-dawn.toml"
]

[window]
  decorations = "Full"
  opacity = 0.92
  blur = true
  padding = { x = 3, y = 3 }
  dynamic_padding = true
  decorations_theme_variant = "Dark"
  option_as_alt = "OnlyLeft"

[font]
  normal = { family = "GeistMono Nerd Font", style = "Regular" }
  bold = { family = "GeistMono Nerd Font", style = "Bold" }
  italic = { family = "GeistMono Nerd Font", style = "Italic" }
  bold_italic = { family = "GeistMono Nerd Font", style = "Bold Italic" }
  size = 14
  offset.y = 10
  glyph_offset.y = 5
  
[selection]
  save_to_clipboard = true

